# Generated by Django 5.2.8 on 2025-11-19 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 10', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='petname',
            field=models.CharField(blank=True, default='user', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 10', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=50),
        ),
    ]
